### ISSUE TITLE
publish some article on devto

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#112]
this will be our test ))

feel free to grab any set of links from Readme that we didn't used before and publish it as a post

examples:

- https://dev.to/atherdon/cool-newsletters-for-developers-part-3-2432
- https://dev.to/atherdon/reading-list-how-to-code-html-for-emails-1lng
- https://dev.to/atherdon/reading-list-github-repositories-for-sending-emails-1702
- https://dev.to/atherdon/reading-list-transactional-emails-2jm9

**Comment by atherdon** [comment]
#83

**Comment by Svitlana007** [comment]
Take a look:

https://dev.to/atherdon/best-email-marketing-tools-for-2022-h7a

**Comment by atherdon** [comment]
wow, looks awesome!

lets then move this article through workflow that I mentioned at #83 
because we can get move traffic juice from it!

**Comment by Svitlana007** [comment]
Ok
