### ISSUE TITLE
migrate tasks into a proper repository

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#113]
we have tasks with outdated category: https://github.com/LLazyEmail/markdown-to-email/issues?q=is%3Aissue+is%3Aopen+react+label%3Areact

we need to move them into this repository: https://github.com/LLazyEmail/nextjs-preview/issues

**Comment by Svitlana007** [comment]
You are sure that I have access to transfer tasks?
![image](https://user-images.githubusercontent.com/109110458/182148189-dd28e0e6-23a1-41f5-8b58-0861e6701c30.png)

**Comment by atherdon** [comment]
we can split it into 2 tasks:
- move tasks into a file
- then we'll move it as one big task

**Comment by atherdon** [comment]
by transferring tasks i mean copy-pasting title & content

**Comment by Svitlana007** [comment]
Ok, i understand. I think i must transferring an issue to another repository

**Comment by Svitlana007** [comment]
But I will do it in the evening - I have to run to my baby.

You can write more tasks for the evening)

**Comment by atherdon** [comment]
sure, take your time and thank you!

will try to think about it

**Comment by Svitlana007** [comment]
Done

Create: "Tasks from markdown-to-email repository.md"

**Comment by atherdon** [comment]
thank you!

**Comment by atherdon** [comment]
btw, you can put links of tasks in PR or share PR links in tasks - it will create a link between them

here are coupons for my git/github courses, feel free to use them if you want

- https://www.udemy.com/course/git-basics-and-merging-process/?couponCode=B6FEEAB79D78EF5C3FE2
- https://www.udemy.com/course/git-workflows-in-depth/?couponCode=2ECB872FCD6241B42403

**Comment by Svitlana007** [comment]
> btw, you can put links of tasks in PR or share PR links in tasks - it will create a link between them
> 
> here are coupons for my git/github courses, feel free to use them if you want
> 
> * https://www.udemy.com/course/git-basics-and-merging-process/?couponCode=B6FEEAB79D78EF5C3FE2
> * https://www.udemy.com/course/git-workflows-in-depth/?couponCode=2ECB872FCD6241B42403

Щиро дякую!!!

**Comment by atherdon** [comment]
its my pleasure
