### ISSUE TITLE
to migrate into readme file

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#114]
https://github.com/LLazyEmail/markdown-to-email/issues/403

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
I think i made a mistake. we need to move it into improvements file :( sorry

**Comment by Svitlana007** [comment]
> I think i made a mistake. we need to move it into improvements file :( sorry

Я теж так подумала, що ви напевне помилились, сорі, що не уточнила, зараз поправлю

**Comment by atherdon** [comment]
done

**Comment by Svitlana007** [comment]
> done

ви самостійно перенесли?)

**Comment by atherdon** [comment]
nope, i think you did it in previous pull request #121 
sorry :) will go out and don't disturb

**Comment by Svitlana007** [comment]
> nope, i think you did it in previous pull request #121
> sorry :) will go out and don't disturb

Все окей))) Вже переношу!)

**Comment by Svitlana007** [comment]
Done. Move it into improvements file
