### ISSUE TITLE
move to improvements

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#117]
https://github.com/LLazyEmail/markdown-to-email/issues/1003

https://github.com/LLazyEmail/markdown-to-email/issues/1337

https://github.com/LLazyEmail/markdown-to-email/blob/main/src/domain/react/replace-markdown/replace-md.js

https://github.com/LLazyEmail/markdown-to-email/blob/main/src/domain/callbacks-factory/index.js

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
thank you! 
I was not able to sleep due to air alarms, so I made some progress in those documents
