### ISSUE TITLE
feel free to move errors, react, improveents into our documentation repository

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#126]

**Comment by Svitlana007** [comment]
Я створила пул реквести, але чомусь "Test deployment" failing, можете пояснити, що не так зробила?

**Comment by atherdon** [comment]
там нужно мне починить. раньше при добавлении файлов мы сразу проверяли чтобы сайт генерировался. сейчас чтото сломалось.

можете сделать таск и повесить его на меня

**Comment by atherdon** [comment]
btw, did you move my pdf file?

**Comment by atherdon** [comment]
please also delete files that were moved away from this repository.

btw, we need to move todo file as well

**Comment by Svitlana007** [comment]
> "Test deployment" failing

Done
https://github.com/LLazyEmail/awesome-email-marketing/issues/134

**Comment by Svitlana007** [comment]
> 

Which one exactly?

**Comment by Svitlana007** [comment]
> btw, did you move my pdf file?

Which one exactly?

**Comment by Svitlana007** [comment]
Створила пул реквести на видалення файлів

**Comment by Svitlana007** [comment]
> btw, we need to move todo file as well

Create pull request

**Comment by atherdon** [comment]
> > btw, did you move my pdf file?
> 
> Which one exactly?

take a look in this folder: https://github.com/LLazyEmail/awesome-email-marketing/tree/main/improvements

**Comment by Svitlana007** [comment]
В мене немає доступу завантажувати файли, хіба що можу створити .md файл

![image](https://user-images.githubusercontent.com/109110458/183148193-c3f862be-cb68-4c34-965c-bd30b2121ef4.png)

**Comment by atherdon** [comment]
i forget about it.
straaange setting. will do it myself
