### ISSUE TITLE
we need to add our linkedin link into major repositories

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#133]
https://www.linkedin.com/company/llazyemail/

plus we can add it into all of our blog posts in documentation website

**Comment by Svitlana007** [comment]
Не до кінця розумію, що мені потрібно зробити... Можете детальніше пояснити?

**Comment by atherdon** [comment]
I want to try to drive some traffic to our Linkedin page. While we don't have a website - this is one place where we can receive a message from a client.

The task is simple: we have a lot of markdown files across our organization - let's put a LinkedIn link into those documents and see if it change something

**Comment by Svitlana007** [comment]
З якого репозиторію брати файли: documentation чи awesome-email-marketing ?

**Comment by atherdon** [comment]
розпочнiть з documentation first.
але я хочу цей лiнк у багатьох мiсцях

**Comment by Svitlana007** [comment]
## [Linkedin page of LLazyEmail](https://www.linkedin.com/company/llazyemail/)

**Comment by atherdon** [comment]
looks good!
let's add it into more repositories

**Comment by Svitlana007** [comment]
add this `## [Linkedin page of LLazyEmail](https://www.linkedin.com/company/llazyemail/)` for all documents in `documentation/blog/`

**Comment by Svitlana007** [comment]
add this `## [Linkedin page of LLazyEmail](https://www.linkedin.com/company/llazyemail/)` for all documents in `documentation/docs/generator/`

**Comment by Svitlana007** [comment]
folder  `documentation/docs` done

**Comment by Svitlana007** [comment]
repositorie `LLazyEmail/documentation` done

**Comment by Svitlana007** [comment]
repositorie 'LLazyEmail/awesome-email-marketing' done

**Comment by atherdon** [comment]
- https://github.com/LLazyEmail/website
- https://github.com/LLazyEmail/nomoretogo_email_template
- https://github.com/LLazyEmail/_trying-lit
- https://github.com/LLazyEmail/markup-generator
- https://github.com/LLazyEmail/subscribe-form
- https://github.com/LLazyEmail/react-plain-template-example
- https://github.com/LLazyEmail/markdown-regex
- https://github.com/LLazyEmail/replacer

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/website

Done, placed the link only in the `.md` file

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/nomoretogo_email_template

Done, placed the link only in the `.md` file

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/_trying-lit

Done, placed the link only in the `.md` file

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/markup-generator

Done, placed the link only in the `.md` file

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/subscribe-form

Done, placed the link only in the `.md` file

**Comment by atherdon** [comment]
perfect!

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/react-plain-template-example

Done, placed the link only in the `.md` file

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/markdown-regex

Done, placed the link only in the `.md` file

**Comment by Svitlana007** [comment]
> * https://github.com/LLazyEmail/replacer

Done, placed the link only in the `.md` file
