### ISSUE TITLE
"Test deployment" failing

### ISSUE THREAD

**Issue by Svitlana007** [LLazyEmail/awesome-email-marketing#134]
![image](https://user-images.githubusercontent.com/109110458/182706682-6403d891-d3cd-48c7-b5fe-26c2fd01a182.png)

**Comment by Svitlana007** [comment]
What here?

**Comment by atherdon** [comment]
sorry, still busy with other tasks.

maybe will just pass it to Vadim, as he will be doing a lot of work tomorrow

**Comment by atherdon** [comment]
started to review it

**Comment by atherdon** [comment]
will be fixed today. closing it
