### ISSUE TITLE
migrate to readme

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#14]
another 2 files: 

https://github.com/LLazyEmail/awesome-email-marketing/blob/main/a.md
https://github.com/LLazyEmail/awesome-email-marketing/blob/main/github.md

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
yes, please move it and delete those files 

cc @Svitlana007

**Comment by Svitlana007** [comment]
Done
