### ISSUE TITLE
reogranize files inside this repo

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#156]
нам нужно "спрятать" почти все файлы, кроме readme - потому что часть из них в этом репозитории временно.

посути важным файлом тут является только readme.md

также нужно посмотреть какие файлы нам ненужны, потому что мы их уже перенесли в documentation(например todo мы вроде перенесли)

**Comment by Svitlana007** [comment]
todo - створила пул реквест для видалення

**Comment by Svitlana007** [comment]
> нам нужно "спрятать" почти все файлы, кроме readme - потому что часть из них в этом репозитории временно.
> 
> посути важным файлом тут является только readme.md

куди їх сховати?) створити для них всіх окрему папку в даному репозиторії?

**Comment by atherdon** [comment]
так

**Comment by Svitlana007** [comment]
https://github.com/LLazyEmail/awesome-email-marketing/blob/main/tasks%20template.md @atherdon цей документ потрібно ще кудись перенести, забула куди ми кидали аналогічний...

**Comment by atherdon** [comment]
цей документ мае бути в documentation repository

**Comment by Svitlana007** [comment]
Done

[Create tasks template.md #88](https://github.com/LLazyEmail/documentation/pull/88)
[Delete tasks template.md #185](https://github.com/LLazyEmail/awesome-email-marketing/pull/185)
