### ISSUE TITLE
move pipeline +gitops files into documentation website

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#157]

**Comment by Svitlana007** [comment]
Create pipeline.md [#61](https://github.com/LLazyEmail/documentation/pull/61)

Done

**Comment by Svitlana007** [comment]
@atherdon `gitops` it wich one?

**Comment by atherdon** [comment]
sorry, i mean https://github.com/LLazyEmail/awesome-email-marketing/blob/main/DevOps.md

**Comment by Svitlana007** [comment]
Ми маємо вже цей файл в репозиторії `[documentation](https://github.com/LLazyEmail/documentation)`
![image](https://user-images.githubusercontent.com/109110458/183512729-3ea66e25-7dd3-4a6f-91b3-39debb9598c3.png)
видалити його з репозиторію `[awesome-email-marketing](https://github.com/LLazyEmail/awesome-email-marketing)`?

**Comment by atherdon** [comment]
так, тому що я вже заплутався якi файли ми перенесли з цього репозиторію
