### ISSUE TITLE
add Transactional to Dev.to

### ISSUE THREAD

**Issue by Svitlana007** [LLazyEmail/awesome-email-marketing#167]
https://github.com/LLazyEmail/awesome-email-marketing/blob/main/Transactional%20Emails.md

**Comment by Svitlana007** [comment]
@atherdon Can I post this article to Dev.to?

**Comment by Svitlana007** [comment]
Вона вже є там
https://dev.to/atherdon/reading-list-transactional-emails-2jm9

**Comment by atherdon** [comment]
> Вона вже є там https://dev.to/atherdon/reading-list-transactional-emails-2jm9

це гарний приклад того, навiшо нам мати матрицю статтей
