### ISSUE TITLE
links

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#17]
- https://raw.githubusercontent.com/LLazyEmail/awesome-newsletters/main/Demand%20Curve.md
- https://raw.githubusercontent.com/LLazyEmail/awesome-newsletters/main/pt-5-building-a-list.md
- https://raw.githubusercontent.com/LLazyEmail/awesome-newsletters/main/repositories%20to%20explore.md

**Comment by Svitlana007** [comment]
Create new file [Create Demand%20Curve.md](https://github.com/LLazyEmail/awesome-email-marketing/commit/83742a964cffcb12b19d209cd58d8870a5f64c5c)

**Comment by Svitlana007** [comment]
Create new file [Create pt-5-building-a-list.md](https://github.com/LLazyEmail/awesome-email-marketing/commit/a78940a37232a4803c3b9c2ef340473f2a734f25)

**Comment by Svitlana007** [comment]
Create new file [Create repositories%20to%20explore.md](https://github.com/LLazyEmail/awesome-email-marketing/commit/1a46f96fe0f0c50d40bca69570af1326b35f479d)

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
closing this task, but can you move it now into readme, please?
