### ISSUE TITLE
move to documentation website

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#174]
https://github.com/LLazyEmail/awesome-email-marketing/blob/main/display-factory%20%2373.md

**Comment by Svitlana007** [comment]
Done

[Create display-factory #73.md #72](https://github.com/LLazyEmail/documentation/pull/72) in documentation

[Delete display-factory #73.md #175](https://github.com/LLazyEmail/awesome-email-marketing/pull/175) in awesome-email-marketing
