### ISSUE TITLE
more docs

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#20]
https://github.com/LLazyEmail/awesome-email-marketing/blob/main/github1.md

https://github.com/LLazyEmail/awesome-email-marketing/blob/main/333.md

https://github.com/LLazyEmail/awesome-email-marketing/blob/main/mobile-browser.md

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
was content moved into the readme file?

if yes, please remove those files as we need them only for temporary use.

**Comment by Svitlana007** [comment]
Done
