### ISSUE TITLE
changes v2

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#37]
1. replace header with "Frontend Development"
![image](https://user-images.githubusercontent.com/1469198/178932716-d0d1d2b1-3005-4462-8209-5758abdf7d0f.png)

---

2. Add sections like:
- Github
- Miscellaneous
- Administration

---

3. links that left in "Great links" move to Blogs or Resources

---

4. Add descriptions to products that don't have them

![image](https://user-images.githubusercontent.com/1469198/178938221-51fcede0-c8dd-4cd2-a0ca-d298c1f02773.png)

![image](https://user-images.githubusercontent.com/1469198/178938257-fd14bf1f-1950-4ce4-9729-3ab56bddf7c7.png)

![image](https://user-images.githubusercontent.com/1469198/178938300-b8fb3214-7ea3-47fa-8c7f-29936a95ad8a.png)

---

5. move to the miscellaneous section for now
![image](https://user-images.githubusercontent.com/1469198/178933300-7c458e2a-a8f9-48fd-a2f1-cbcb44fdfc4d.png)

---

6. move to github section

![image](https://user-images.githubusercontent.com/1469198/178938661-3959cc50-f5d7-4a5a-b8c4-af27014e3108.png)

---

7. move to zapier

![image](https://user-images.githubusercontent.com/1469198/178940921-1afa8479-a961-486f-abfe-b132f3e3feee.png)

---

8. all products should have only first char upper score

![image](https://user-images.githubusercontent.com/1469198/178941741-9c75abf2-535e-4b63-b34e-b72decca5767.png)

![image](https://user-images.githubusercontent.com/1469198/178941760-fdca76c9-3a38-4a86-b7fc-00b460b25ecf.png)

**Comment by Svitlana007** [comment]
@atherdon прийміть, будь ласка, усі створені мною попередні пул реквести, щоб я могла приступити до виконання даної задачі, а то є пул реквести на внесення змін в головний файл і він ще не підтверджений - я трішки розгубилась, що вже зроблено, а що потрібно поправити.

Дякую!

**Comment by atherdon** [comment]
зараз подивлюсь

**Comment by atherdon** [comment]
sorry for slow turnaround

**Comment by atherdon** [comment]
це буде багато змiн у цьому таску

**Comment by Svitlana007** [comment]
Done
