### ISSUE TITLE
reorganization

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#50]
**1. move to miscellaneous for now**
![Screenshot_2](https://user-images.githubusercontent.com/1469198/179349272-946e9131-092c-41e2-85ac-6bbfbcc25f41.jpg)

![image](https://user-images.githubusercontent.com/1469198/179350164-6f98238b-863b-4ab9-8056-e1aa77f70b5a.png)

---

**3. перенос в секцию гитхаб**
![Screenshot_4](https://user-images.githubusercontent.com/1469198/179349498-68ea460b-cc6d-4e5f-ad14-2f9cb313deb8.jpg)

---

**4. нужно перенести в frontend section. а куда она делась.**

![Screenshot_5](https://user-images.githubusercontent.com/1469198/179349554-d0d45933-3af6-48e6-a7f9-27850e9d7799.jpg)

---

**5. move to email producs**

![Screenshot_6](https://user-images.githubusercontent.com/1469198/179349588-72db6dc6-4da7-46c7-b68f-c783b42815fa.jpg)

![image](https://user-images.githubusercontent.com/1469198/179349812-97b1c81a-9c31-4591-8280-22a76398629b.png)

![image](https://user-images.githubusercontent.com/1469198/179350115-5e8eb9e2-52c8-4727-929f-6ffd64ab6ec0.png)

---

**6. move to github as sub-sections**

![image](https://user-images.githubusercontent.com/1469198/179349717-0ac5875e-914c-42a5-85f8-74afbf432644.png)

![image](https://user-images.githubusercontent.com/1469198/179349738-a452e94f-b6b1-4c83-9e17-51f750a0dc3b.png)

![image](https://user-images.githubusercontent.com/1469198/179349754-fe6f0738-b6b4-44a3-a5b3-c35232538ad4.png)

![image](https://user-images.githubusercontent.com/1469198/179349761-e0a0a32c-e68e-407e-8f85-ee904898c621.png)

![image](https://user-images.githubusercontent.com/1469198/179349846-87a40f79-095d-4031-b63d-3a401d6e5652.png)

---

**7. add heading** "[Demand Curve: Tested tactics for growing newsletters](https://techcrunch.com/2021/08/03/demand-curve-tested-tactics-for-growing-newsletters/)" 

![image](https://user-images.githubusercontent.com/1469198/179349903-ee3b15e2-e9f0-46ab-afec-405488c27169.png)

---

**2. вся ця секция относится к Metrics**
![Screenshot_3](https://user-images.githubusercontent.com/1469198/179349276-74267179-a5c0-481d-9b28-f5b69175809e.jpg)

2.1 rename Metrics to "Newsletter Metrics"

2.2 add subheading "Basics"
![image](https://user-images.githubusercontent.com/1469198/179349971-c9f69911-2bf7-4742-b6a8-3f7c96febbbf.png)

2.3 add subheading "How To Measure Your Newsletter Performance"
![image](https://user-images.githubusercontent.com/1469198/179350008-3a4b678c-2de7-4a31-8486-2bd948ee21fc.png)

2.4 make it as a subheader to Metrics
![image](https://user-images.githubusercontent.com/1469198/179350041-580c8537-be5a-41b3-8537-64f626b65b8e.png)

---

8. connect with "Sister repository" link and keep it in the end of this repository
![image](https://user-images.githubusercontent.com/1469198/179350079-d8919f87-0adf-48c0-9a35-1ff496e400ce.png)

---

9. move to resources section
![image](https://user-images.githubusercontent.com/1469198/179350095-71764888-62f1-4823-8ce1-0e2c50b14e45.png)

---

10. move to frontend section where other templates located

![image](https://user-images.githubusercontent.com/1469198/179350136-e6ab5676-7b29-4a6c-b61c-f280f914b921.png)

---

11. move to Administration as a subsections

![image](https://user-images.githubusercontent.com/1469198/179350192-a684ec1e-c4c0-4a43-96aa-4624f5b6f1d6.png)

**Comment by Svitlana007** [comment]
4. нужно перенести в frontend section. а куда она делась. - ми хіба не перейменували її на ### Frontend Development???

**Comment by atherdon** [comment]
я знайшов цю секцiю, вона була нижче розташована. 
в нас такий довгий файл - ще не дуже гарно орiенуюсь у ньому. 
але це дуже гарно - бачу що багато контенту я назбирав за рiк.

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
thank you. just merged latest pull request
