### ISSUE TITLE
move content and images into this repository

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#54]
1. Move content from those tasks into makrdown file
- https://github.com/LLazyEmail/nomoretogo_email_template/issues/63
- https://github.com/LLazyEmail/markdown-to-email/issues/970
- https://github.com/LLazyEmail/markdown-to-email/issues/1038
- 

file: https://github.com/LLazyEmail/awesome-email-marketing/blob/main/errors.md
you can create images folder and upload files there

- https://github.com/LLazyEmail/markdown-to-email/blob/main/images/default-method-with-errors-for-protection.png
- https://github.com/LLazyEmail/markdown-to-email/blob/main/images/MindMap1.png
- https://github.com/LLazyEmail/markdown-to-email/blob/main/images/issue-with-jest-because-babel-is-not-updated.png
- https://github.com/LLazyEmail/markdown-to-email/blob/main/images/file-just-for-organizing-output-warnings.png
- https://github.com/LLazyEmail/markdown-to-email/blob/main/images/parser-runs-from-build-so-hard-to-trace.png
- https://github.com/LLazyEmail/markdown-to-email/blob/main/images/object-init-with-lookout-for-errors.png

please create a pull request after that.

And I'll create an example about how to display those images in our md files.

---

2. display images in error file
3. more details will add later to this task

**Comment by Svitlana007** [comment]
@atherdon перепрошую, але я напевне погано вас зрозуміла... я мала вміст цих трьох задач перенести в файл https://github.com/LLazyEmail/awesome-email-marketing/blob/main/errors.md, а не створювати нові файли.

Переробити?)

**Comment by atherdon** [comment]
> @atherdon перепрошую, але я напевне погано вас зрозуміла... я мала вміст цих трьох задач перенести в файл https://github.com/LLazyEmail/awesome-email-marketing/blob/main/errors.md, а не створювати нові файли.
> 
> Переробити?)

все добре, це не проблема. Так, треба зробити одним файлом, тому що ми потім перенесемо файли у інше місце

**Comment by Svitlana007** [comment]
Зробила одним файлом, прийміть пул реквест

**Comment by atherdon** [comment]
добре. ми також маємо скачати усі файли до цього репозіторія про всяк випадок

**Comment by Svitlana007** [comment]
![image](https://user-images.githubusercontent.com/109110458/179425749-063d2468-7ecb-4852-9598-afb460ab3af0.png)

ще з цим мені допоможіть, бо не можу загуризити зображення

**Comment by atherdon** [comment]
хм, добре, я перенесу сам файли. це щось нове вони зробили...

**Comment by Svitlana007** [comment]
@atherdon Тоді з даного завдання ніби все, чекаю подальших вказівок

**Comment by atherdon** [comment]
так, зараз подивлюсь

**Comment by atherdon** [comment]
файли теперь є: https://raw.githubusercontent.com/LLazyEmail/awesome-email-marketing/main/images%20folder/MindMap1.png

**Comment by Svitlana007** [comment]
> файли теперь є: https://github.com/LLazyEmail/awesome-email-marketing/tree/main/images%20folder

так, бачила, дякую!

**Comment by atherdon** [comment]
у цей файл треба добавити усі малюнки що є https://raw.githubusercontent.com/LLazyEmail/awesome-email-marketing/main/images%20folder/images.md

**Comment by Svitlana007** [comment]
> у цей файл треба добавити усі малюнки що є https://raw.githubusercontent.com/LLazyEmail/awesome-email-marketing/main/images%20folder/images.md

В цей файл https://github.com/LLazyEmail/awesome-email-marketing/blob/main/errors.md?

**Comment by atherdon** [comment]
> > у цей файл треба добавити усі малюнки що є https://raw.githubusercontent.com/LLazyEmail/awesome-email-marketing/main/images%20folder/images.md
> 
> В цей файл https://github.com/LLazyEmail/awesome-email-marketing/blob/main/errors.md?

можна в цей, так
