### ISSUE TITLE
reorganization pt3

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#59]
**1. move to Zapier section**

![image](https://user-images.githubusercontent.com/1469198/179423946-063cfb6b-d53c-4ffe-8a50-57e1565db348.png)
 

---

**2. move to Metrics and delete "Stats" heading**

![image](https://user-images.githubusercontent.com/1469198/179423958-af221820-42a2-4643-b963-5f3f39d92c5c.png)

---

**3. rename Zapier with integrations to "Zapier Blog"**
---

**4. formatting is broken**

![image](https://user-images.githubusercontent.com/1469198/179424045-5055d48c-c31a-4b1c-bf9f-6d5421a9327a.png)

![image](https://user-images.githubusercontent.com/1469198/179424360-6811ab5b-1f93-4fa9-b772-db20d1d05b48.png)

---

**6. rename Repositories related to emails to "GitHub repositories related to email marketing"**

---

7.  must be a subsections of Github
![image](https://user-images.githubusercontent.com/1469198/179424340-2d4ef595-e29b-4d8a-ac70-0f186672964d.png)
![image](https://user-images.githubusercontent.com/1469198/179424354-823c3dc5-cc5a-4ff5-8cf4-0e4248c4235a.png)

---

8. rename Links to read to "DNS DKIM record"

![image](https://user-images.githubusercontent.com/1469198/179424384-7af7e819-8742-4250-8e5a-1ace38ac73a0.png)

---

9. we have unnesessary symbol **\"**
![image](https://user-images.githubusercontent.com/1469198/179424388-b5bbfde3-0317-4793-af1d-fdefa1dad607.png)

---

10. delete this heading 
![image](https://user-images.githubusercontent.com/1469198/179424435-6421104a-c285-44de-98c6-c869e064946a.png)

11. move to a list with github repositories
![image](https://user-images.githubusercontent.com/1469198/179424458-630292f9-b748-433f-b6e7-16bcc3aa9eb9.png)

---

12. move to Resources
![image](https://user-images.githubusercontent.com/1469198/179424481-672ba153-6575-421d-b935-e8c3531d3bf7.png)
![image](https://user-images.githubusercontent.com/1469198/179424502-4c767159-e5b0-4edd-b21a-5c0c03b2b680.png)
![image](https://user-images.githubusercontent.com/1469198/179424507-c0828b8d-8f51-4224-a267-4076a3c2c4a9.png)
![image](https://user-images.githubusercontent.com/1469198/179424528-0f8a1635-20aa-4ba0-a9c1-698e9a47b3fd.png)

---

13.

**Comment by Svitlana007** [comment]
Все виконано окрім:
must be a subsections of Github
що це означає, бо станом на зараз це супсекції Github чи воно має бути не заголовком і всі лінки під Github?

![image](https://user-images.githubusercontent.com/109110458/179424949-799fea04-7083-4d6a-97d0-ba55a959130f.png)

**Comment by atherdon** [comment]
тоді не треба нічого робити с checkers зараз. я дивився з телефону спочатку, тому непобачив

**Comment by atherdon** [comment]
is it done, right?
