### ISSUE TITLE
tell me if you able to edit this repository

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#69]
https://github.com/LLazyEmail/.github/

While i didnt find out what to do next with this repository - we need help with organizing data in our main readme.

if you can edit it - cool - then please take a look and do some changes, in order to make it looks better.

Later I'll collect my notes and do a task with step-by-step instructions

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
thank you
