### ISSUE TITLE
changes pt3

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#70]
**1. change to "Best Email Marketing Tools for 2022"**
![image](https://user-images.githubusercontent.com/1469198/180185146-45e4f927-ee70-415b-82a3-fe1c19fe830d.png)

**2. delete this line and combine lists**
![image](https://user-images.githubusercontent.com/1469198/180185305-7b2b7898-1c8c-412e-8da6-e23aa9a4ffaa.png)

**3. delete this header and combine this list with "best marketing tools"**

![image](https://user-images.githubusercontent.com/1469198/180185493-fb7154a1-df61-47f6-87ac-b5c5356b2a89.png)

**4.  remove**
`We recommend to you pay more attention to these points`

**5. move my articles "Arthur Tkachenko articles" under Miscellaneous**

**6. formatting issue**

![image](https://user-images.githubusercontent.com/1469198/180186121-cb147e1e-d087-41b7-92b2-919fa804b5c7.png)

**7. rename to "open source tools" and add links**

https://www.mautic.org/
https://www.sympa.org/
https://www.openemm.org/doku.php
https://sendportal.io/
https://lightmeter.io/

![image](https://user-images.githubusercontent.com/1469198/180188141-bc4578dd-5366-45e8-98c9-0d6e4a6df7ac.png)

---

**8. rename to DNS DKIM Records**
![image](https://user-images.githubusercontent.com/1469198/180188589-aac27ba0-f91e-4c51-8469-d8640cf68b4f.png)

---

**9. add sub-sections to Transactional Emails**
- basics
- advanced
- tools

**10. move to Resources section**

![image](https://user-images.githubusercontent.com/1469198/180193887-0c32c50d-555d-46d7-8bc1-4f33d7914453.png)

**10. check the Transactional section for duplicates**
![image](https://user-images.githubusercontent.com/1469198/180194148-9f9956d3-ab6e-4bbb-b01f-fe381844f76d.png)

11. **create a section "Similar awesome lists"** in the end of our Readme file, change titles and move those links into this section
![image](https://user-images.githubusercontent.com/1469198/180194530-e2e68e53-aef3-4e0c-ae09-de5f294ef08f.png)

**Comment by Svitlana007** [comment]
Готово. 

9. add sub-sections to Transactional Emails

basics
advanced
tools
________________________________
цього не робила, бо такі вже є (оновила "Table of Contents", то зможете побачити)

8. rename to DNS DKIM Records
image
_______________________________
тут теж такий заголок вже був, тому тільки об'єднала

**Comment by atherdon** [comment]
thank you!
