### ISSUE TITLE
preparimg content for articles

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#75]
**intro**

https://user-images.githubusercontent.com/1469198/180378260-68044d8d-7888-4fd2-af54-4ca1df159502.mp4

articles from video:
- https://hackernoon.com/cool-resources-for-sending-emails
- https://hackernoon.com/cool-newsletters-for-developers-part-1

**Comment by Svitlana007** [comment]
Pull request for creating files^
1. [Create Demand Curve: Tested tactics for growing newsletters.md #79](https://github.com/LLazyEmail/awesome-email-marketing/pull/79)
2. [Create Frontend Development.md #80](https://github.com/LLazyEmail/awesome-email-marketing/pull/80)
3. [Create Github.md #81](https://github.com/LLazyEmail/awesome-email-marketing/pull/81)
4. [Create Transactional Emails.md #82](https://github.com/LLazyEmail/awesome-email-marketing/pull/82)

**Comment by Svitlana007** [comment]
Жодної з цих ссилок немає в файлі [Awesome-email-marketing](https://github.com/LLazyEmail/awesome-email-marketing/blob/main/README.md)
![image](https://user-images.githubusercontent.com/109110458/180571447-1d0c197d-e23e-4042-bfba-0fbe768e240c.png)

**Comment by atherdon** [comment]
Так треба зробити 2 роздiла (Drip blog, Automizy Blog), як

![image](https://user-images.githubusercontent.com/1469198/180601732-d1133137-4326-4131-822c-078686e79d6c.png)

**Comment by Svitlana007** [comment]
Done
