### ISSUE TITLE
copy content into our documentation page

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#76]
put files into this folder, later we'll handle it - https://github.com/LLazyEmail/documentation/tree/main/docs

https://github.com/LLazyEmail/.github/blob/main/profile/README.md

https://github.com/LLazyEmail/awesome-email-marketing/blob/main/README.md

and when I'll accept pull request, pages will appear on this website https://llazyemail.github.io/documentation/

**Comment by Svitlana007** [comment]
@atherdon I can not do this
![image](https://user-images.githubusercontent.com/109110458/180869563-692f5e87-b667-4f82-b320-7030a7637dd6.png)

**Comment by Svitlana007** [comment]
@atherdon What should I do with this task?

**Comment by atherdon** [comment]
can you create a fork of it and try to submit some changes?

**Comment by Svitlana007** [comment]
Гілку створила, але як тути помістити дані файли?

**Comment by atherdon** [comment]
зробю вiдео зараз

**Comment by atherdon** [comment]
https://user-images.githubusercontent.com/1469198/181763890-18909a25-e3f0-41e6-bc6f-868643509c43.mp4

**Comment by Svitlana007** [comment]
Створила папку "test" а в ній файл "Create Collections of articles.md", будь ласка, гляньти чи все ок

**Comment by atherdon** [comment]
дивлюся

**Comment by Svitlana007** [comment]
@atherdon перенести ці файли в папку "docs":
https://github.com/LLazyEmail/.github/blob/main/profile/README.md

https://github.com/LLazyEmail/awesome-email-marketing/blob/main/README.md

???

**Comment by atherdon** [comment]
yes

**Comment by Svitlana007** [comment]
Один файл перенесла і пул реквест створився ок, а інший щось підвисло, гляньте, будь ласка

**Comment by Svitlana007** [comment]
![image](https://user-images.githubusercontent.com/109110458/183288288-7703b723-d208-4aba-b7f8-aff02fb52ccd.png)

Файли перенесені, можна закривати задачу)

**Comment by atherdon** [comment]
closing it. But can we rename those files, please?

**Comment by Svitlana007** [comment]
> closing it. But can we rename those files, please?

Done
1. Rename README.md to Awesome-email-marketing.md [#58](https://github.com/LLazyEmail/documentation/pull/58)
2. Rename githubREADME.md to LLazyEmail Documentation.md [#59](https://github.com/LLazyEmail/documentation/pull/59)
