### ISSUE TITLE
небольшое улучшение файлов с задачами

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#88]
перед тем как я добавлю информацию по задачам, которые мы перенесли - хочу немного улучшить читабельность наших файлов errors, improvements, react

https://user-images.githubusercontent.com/1469198/180626046-a4f81b9d-f9c3-45b2-a9bc-1542da573e5f.mp4

**Comment by Svitlana007** [comment]
Done
