### ISSUE TITLE
help me with retiting some of our subsections

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#96]
мне ненравятся некоторые названия у наших секций и это тормозит меня от выкладки нашего репозитория.

возможно вы сможете посмотреть на наш readme свежим взглядом и предложить некоторые изменения.
Давайте потратим на это какое то время - лишним это не будет.

**Comment by Svitlana007** [comment]
@atherdon I propose the following changes:
1. Have ecommerce integration - Marketing automation platform wich have ecommerce integration
2. Marketing automation - Automation email marketing platform
3. Tools - Tools for effective works with e-mail
4. Resources - Resources wich giv answers about importance e-mail in your business
5. Getvero - Getvero about Email Marketing
6. Revue - Revue: fears and risks
7. Github - Github about Email Marketing
8. Basics - Basics in Email Marketing
9. Advanced - All about effective email marketing
10. Reasons - Reasons to use email newsletters
11. Questions - Frequently asked questions (_Although it seems to be the norm_)
12. Similar awesome lists - Awesome lists

P.S. In my opinion, the headlines simply lacked a greater explanation of what he was about

**Comment by atherdon** [comment]
Please proceed forward with those changes.
I like most of them - will take a look tomorrow after merging PRs

**Comment by Svitlana007** [comment]
@atherdon Make these changes to the document?

**Comment by atherdon** [comment]
Yes, please

**Comment by Svitlana007** [comment]
Done
