### ISSUE TITLE
найти и добавить дополнительных статей в секции

### ISSUE THREAD

**Issue by atherdon** [LLazyEmail/awesome-email-marketing#97]
в этом документе есть важные разделы, информации по которым есть много в интернете.
https://github.com/LLazyEmail/awesome-email-marketing/blob/main/latest.md

предлагаю добавить 5-6 статей в несколько секций, а когда доделаем - перенесем эти ссылки в основной наш документ.
просто погуглите в разных вариантах и добавьте статьи без дупликатов. А я в пулл реквесте посмотрю ссылки, которые вы нашли

- Personalization
- Newsletters lead generation
- Lifecycle Email Marketing

**Comment by Svitlana007** [comment]
Added 6 articles to the section "**Personalization and slides**":
- [Email Personalization: 23 of the Best Personalized Email Examples](https://blog.hubspot.com/blog/tabid/6307/bid/34146/7-excellent-examples-of-email-personalization-in-action.aspx)

- [25 Tips for Perfecting Your E-mail](https://www.inc.com/guides/2010/06/email-etiquette.html)

- [What is a Personalized Email? Definition, Tactics & Examples](https://respona.com/blog/personalized-email/)

- [What is a Personalized Email: Definition and Guide](https://sendpulse.com/support/glossary/personalized-email)

- [The power of personalized emails: A guide for marketers](https://www.mailjet.com/blog/email-best-practices/personalized-emails/)

- [10 Email Personalization Hacks: How to Grab a Prospect’s Attention](https://www.cience.com/blog/email-personalization-hacks)

**Comment by Svitlana007** [comment]
Added 6 articles to the section "**Newsletters lead generation**":
- [The best way to generate leads using email newsletter advertising](https://www.thedrum.com/industryinsights/2022/05/11/the-best-way-generate-leads-using-email-newsletter-advertising)

- [How to generate more leads with a Monthly Newsletter](https://leadsbridge.com/blog/how-to-generate-more-leads-with-a-monthly-newsletter/)

- [12 Creative Lead Generation Strategies for Your Business](https://www.wix.com/blog/amp/2019/10/lead-generation-strategies?utm_source=google&utm_medium=cpc&utm_campaign=13708482660^124757113592&experiment_id=^^530755701287^^_DSA&gclid=Cj0KCQjwxIOXBhCrARIsAL1QFCZGTXqgzInNLgx5J1JS54qmoWlhlzsdkdnlsVc3zmWnjgOp18MsqGkaAkBWEALw_wcB)

- [4 ways to generate leads with newsletters](https://www.randallreilly.com/4-ways-to-generate-leads-with-newsletters/)

- [How to Generate High-Quality Leads Using Automation](https://www.leadfeeder.com/blog/how-to-generate-leads-automation/)

- [7 Lead Generation Strategies that Work for Startups](https://www.wordstream.com/blog/ws/2014/10/15/lead-generation-strategies)

**Comment by Svitlana007** [comment]
Added 7 articles to the section "**Lifecycle of**":
- [The Anatomy of a Perfect Lifecycle Email](https://www.smartmail.io/resources/anatomy-perfect-lifecycle-email/)

- [Lifecycle Email Marketing for E-commerce and D2C Brands](https://www.mailmodo.com/guides/lifecycle-email-marketing/)

- [What is customer lifecycle marketing?](https://www.smartinsights.com/ecommerce/web-personalisation/what-is-lifecycle-marketing/)

- [5 Must-Have Email Lifecycle Campaigns and How to Build Them](https://www.mailcharts.com/blog/lifecycle-campaigns)

- [Customer Lifecycle Marketing](https://www.optimove.com/resources/learning-center/customer-lifecycle-marketing)

- [LIFECYCLE EMAIL MARKETING: THE ULTIMATE GUIDE (WITH 250 EXAMPLES)](https://chainlinkmarketing.com/lifecycle-email-marketing/)

- [9 Must-Have Lifecycle Email Marketing Programs for Retailers](https://iterable.com/blog/9-must-have-lifecycle-email-marketing-programs-for-retailers/)

**Comment by Svitlana007** [comment]
Create pull request

**Comment by atherdon** [comment]
looks good

**Comment by atherdon** [comment]
I think we are ready to move content from latest.md into readme

**Comment by Svitlana007** [comment]
Done

**Comment by atherdon** [comment]
can you move it into our readme and delete this file?

**Comment by Svitlana007** [comment]
I have already moved 
![image](https://user-images.githubusercontent.com/109110458/181830010-681b7321-a02f-4255-893c-faf4fe2a01a4.png)

**Comment by Svitlana007** [comment]
File delete

**Comment by atherdon** [comment]
thanks!
